version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # API REST
      - "6334:6334"  # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: pg-retail-brain
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: retailBrain
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  qdrant_data:
  pgdata:
